### ISSUE TITLE
Allow to configure OAuth apps

### ISSUE THREAD

**Issue by chirauki** [abiquo/abiquo-cookbook#63]
Useful for example for M and other integrations.

**Comment by nacx** [comment]
I see this as an issue of the API cookbook instead of one here. To configure OAuth apps you have to create and authorize them, and that requires a conversation with the Abiquo API. This cookbook for provisioning Abiquo platforms, but IMO things like this are outside of the scope of this one and should be deferred to the API cookbook.

**Comment by chirauki** [comment]
Totally agree. I was thinking the same today.

**Comment by nacx** [comment]
Closing as this will be implemented in the API cookbook.
